name: Integration Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: 17
        distribution: 'adopt'
        java-package: 'jdk'
        architecture: 'x64'
        check-latest: false
        server-id: 'github'
        server-username: ${{ github.actor }}
        server-password: ${{ github.token }}
        overwrite-settings: true
        job-status: 'success'

    - name: Set up Docker Compose
      run: sudo apt-get -y install docker-compose

    - name: Build and Start Services
      run: docker-compose up -d --build

    - name: Wait for Services to be Healthy
      run: |
        echo "Waiting for backend-service to be healthy..."
        docker logs carbackend
        while ! curl -sSf http://localhost:8080; do
          sleep 10
        done

    - name: Run Integration Tests
      run: ./gradlew :test -S

    - name: Stop Services
      run: docker-compose down
      
  upload-artifacts:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download Backend Artifact
      uses: actions/download-artifact@v2
      with:
        name: backend-jar
        path: backend/build/libs

    - name: Upload Backend Artifact to Repository
      uses: actions/upload-artifact@v2
      with:
        name: backend-jar
        path: backend/build/libs/backend.jar
